# This is a simplified travis.yml for the gh-pages branch.  In
# particular, it can be very different from the version on the master
# branch.  We don't really need to do anything here except be sure
# that we ask Travis CI to run on the gh-pages branch.  Without it,
# the build will appear to fail.

language: python
sudo: false
python:
  - "2.7"

install:
  # Do nothing
  - true
 
script:
  # Do nothing
  - true

branches:
  only:
  - gh-pages
